FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum .
RUN go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 go build -o manager ./cmd/manager/


FROM gcr.io/distroless/static-debian13

COPY --from=builder /app/manager /manager

ENTRYPOINT ["/manager"]
