FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum .
RUN go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/

ARG TARGETARCH
RUN CGO_ENABLED=0 GOARCH=${TARGETARCH} go build -o plugin ./cmd/plugin/


FROM debian:13-slim

RUN apt-get update && apt-get install -y usbip udev && apt-get clean && rm -rf /var/lib/apt/lists

COPY --from=builder /app/plugin /plugin

ENTRYPOINT ["/plugin"]
