apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.driverName | default "usbip" }}
  labels:
    {{- include "dra-usbip-driver.labels" . | nindent 4 }}
spec:
  selectors:
  - cel:
      expression: device.driver == {{ .Values.driverName | default "usbip.diamond.ac.uk" | quote }}
