apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dra-usbip-driver.fullname" . }}-manager
  labels:
    {{- include "dra-usbip-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dra-usbip-driver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "dra-usbip-driver.labels" . | nindent 8 }}
        app.kubernetes.io/component: manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dra-usbip-driver.serviceAccountName" . }}-manager
      containers:
        - name: manager
          image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          command: ["/manager"]
          args:
          {{- range .Values.manager.agents }}
            - --agent={{ . }}
          {{- end }}
          {{- with .Values.manager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
