apiVersion: v2
name: dra-usbip-driver
description: >-
  Installs the DRA USB/IP driver, which allows sharing USB devices that are exposed by the DRA USB/IP Agent.
  The driver consists of two components: a manager that runs as a Deployment and a plugin that runs as a DaemonSet.
  The manager polls the agents for USB device information and creates ResourceSlice objects in the cluster.

type: application
version: 0.1.1
# NOTE: the CI replaces appVersion with the current git tag.
appVersion: "0.1.1"
