name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  test:
    uses: ./.github/workflows/_test.yml

  container:
    needs: test
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  helm:
    uses: ./.github/workflows/_helm.yml
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: write
